apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-web
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: ongf/team02-app:latest
        imagePullPolicy: Always  # IfNotPresent를 Always로 변경 (보안/신뢰성)
        ports:
        - containerPort: 8000
        # ---------------------------------------------------------
        # 보안 컨텍스트 추가
        securityContext:         
          allowPrivilegeEscalation: false  
          runAsNonRoot: true
          runAsUser: 1000               
          capabilities:
            drop: ["ALL"]                  
        # 
        # ---------------------------------------------------------
        # 가용성 향상
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        # ---------------------------------------------------------
        resources:
          limits:
            cpu: "200m"        
            memory: "256Mi"
          requests:
            cpu: "100m"        
            memory: "128Mi"
        env:
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fastapi-db-secret
              key: db-password
        - name: DB_HOST
          value: "postgres-service.db"  
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "board"
        # 제미나이 API 키
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: web-secret
              key: api-key
        ports:
        - containerPort: 8000

        # 컨테이너 내부의 저장소 연결 (컨테이너 설정 안에 포함)
        volumeMounts:                      
        - name: db-persistent-storage
          mountPath: /app/database         # 앱이 데이터를 저장하는 폴더
        # ---------------------------------------------------------

      # 실제 서버 하드의 저장소 정의 (containers: 와 같은 레벨)
        volumes:                             
        - name: db-persistent-storage
          hostPath:
            path: /home/user/kang-inho/db-data  # 서버(Ubuntu) 실제 폴더
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-web
  namespace: web
spec:
  type: NodePort  
  selector:
    app: fastapi
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080  
